language: objective-c
osx_image: xcode8.3
xcode_project: WaniPersistance.xcodeproj
xcode_scheme: WaniPersistance
xcode_sdk: iphonesimulator10.3
before_install:
  - carthage bootstrap
script:
  - set -o pipefail && xcodebuild -project WaniPersistance.xcodeproj -scheme WaniPersistance -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.3,name=iPhone SE' test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
